### ISSUE TITLE
Pls fix

### ISSUE THREAD

**Issue by Vuurvos1** [ralfz123/portfolio#1]
Update background URL to to minified version of image: https://github.com/ralfz123/portfolio/blob/master/css/layout.css#L38
Update this link to point to the correct GitHub page: https://github.com/ralfz123/portfolio/blob/master/index.html#L668

![alt text](https://i.giphy.com/media/vUO3OogY5WwXS/giphy-downsized.gif)

**Comment by RowinRuizendaal** [comment]
![https://media.giphy.com/media/tdeN0X1QTgEG4/giphy-downsized.gif](https://media.giphy.com/media/tdeN0X1QTgEG4/giphy-downsized.gif)

**Comment by ralfz123** [comment]
Thanks Sam, I'll fix it! 

🔥  🔥  🔥
